### ISSUE TITLE
Getting error on the netscaler_save_config module on missing documentation 

### ISSUE THREAD

**Issue by sanket4373** [networktocode/netscaler-ansible#20]
I am getting the below error while running the below command. Am i missing something?

```
$ ansible-doc netscaler_save_config
ERROR! module netscaler_save_config missing documentation (or could not parse documentation): 'options' ```

**Comment by jmcgill298** [comment]
@sanket4373 can you please provide the output from `ansible --version`?

**Comment by shashank-srinivas** [comment]
@jmcgill298 I'm working with @sanket4373 on this. This is the output of `ansible --version`

```
$ ansible --version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/shassrin/work/src/']
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```
We're both trying to execute this locally from our macbooks.

**Comment by jmcgill298** [comment]
can you provide the path to the Netscaler modules?

**Comment by shashank-srinivas** [comment]
@jmcgill298 `/Users/shassrin/work/src/netscaler-ansible/library`

**Comment by jmcgill298** [comment]
It appears that 2.3.2 changes a little bit of the behavior of how the docstring errors are handled. I am checking them all and will update shortly.

**Comment by shashank-srinivas** [comment]
> It appears that 2.3.2 changes a little bit of the behavior of how the docstring errors are handled. I am checking them all and will update shortly.

Is there a confirmed working version of python that we can use in the meantime?

**Comment by jmcgill298** [comment]
Sorry, I meant the version of Ansible. I have merged the fixes, so you can pull down the updates and it should work.

**Comment by sanket4373** [comment]
Thanks for fixing it @jmcgill298 : It is working now!

**Comment by jmcgill298** [comment]
thanks for reporting 
@sanket4373 @anendlesswaltz
